### ISSUE TITLE
Translating to C#

### ISSUE THREAD

**Issue by petrasvestartas** [Yisaer/Nest4J#4]
Hi,

I am .NET user.
I would like to translate SVGNet library to C# language.

I noticed that you javascript version is more readable.
Are there any elements in the code that are very specific to javascript? Or do you think it is totally doable to translate into C# since those two languages are very similar?

**Comment by Yisaer** [comment]
Actually Nest4J is a java version not javascript version for SVGNest. 
If you want to translate SVGNest into C# based on a javascript version. It's better to get further detail in [SVGNest issues](https://github.com/Jack000/SVGnest/issues)
If you want to make a C# SVGNest algorithm based on my Nest4J , obviously,a java version , I think there is no difference between the java verison and C# version in logical computation like some  computation geometry algorithms , NFP algorithm and GA algorithm.
The only reason I choose java is I am more familiar with it. 
Further more , there is easier to use Java 8 Stream API to optimize NFP generating effiency in mutiple thread opertion for me.
And in Nest4J , i used a Clipper-Lib founded in Github. For C# version , you can use a [C# Clipper-Lib](http://www.angusj.com/delphi/clipper.php) provided officially.

**Comment by Yisaer** [comment]
So I think it is totally feasible for to port Nest4J into a C# version if you want to.
