### ISSUE TITLE
如何构建圆形板件

### ISSUE THREAD

**Issue by f627422467** [Yisaer/Nest4J#8]
您好，请问如何在Nest4J中构建圆形或者圆环型的板件？

**Comment by Yisaer** [comment]
Simulated by a List of points in `NestPath` @f627422467

**Comment by f627422467** [comment]
感谢您的开源，我基于您的算法，做出一套适用SVG的开料优化的解决方案，目前也正在逐步开源，感兴趣的伙伴可以前往[NestTool](https://github.com/f627422467/NestTool)   再次感谢您的分享！
